import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";


export const metadata: Metadata = {
  title: "RoamifyAI: Personalized AI Trip Planner",
  description: "Generated by create next app",
};

const manrope=Manrope({subsets:['latin']});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/favicon.png" />
        </head>
        <body
          className={manrope.className}
        >
          <Provider> 
            {children} 
          </Provider>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
