import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
// remove the default Provider import — use the named provider you implemented
import { UserDetailProvider } from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "./ConvexClientProvider";

export const metadata: Metadata = {
  title: "RoamifyAI: Personalized AI Trip Planner",
  description: "Generated by create next app",
};

const manrope = Manrope({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link rel="icon" href="/favicon.png" />
        </head>
        <body className={manrope.className}>
          <ConvexClientProvider>
            {/* <-- USER DETAIL PROVIDER MUST WRAP CHILDREN */}
            <UserDetailProvider>
              {children}
            </UserDetailProvider>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
